# Generated by Django 4.2.3 on 2023-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_module_custompermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custompermission",
            name="permission",
        ),
        migrations.AddField(
            model_name="custompermission",
            name="permission",
            field=models.ManyToManyField(to="auth.permission"),
        ),
    ]
