# Generated by Django 4.2.3 on 2023-08-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinancialRecordTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
