# Generated by Django 4.2.3 on 2023-08-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0003_dailyfinancialrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyfinancialrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyFinancialRecordTest',
        ),
        migrations.DeleteModel(
            name='DailyFinancialRecord',
        ),
    ]
