# Generated by Django 4.2.3 on 2023-08-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0004_dailyexpenses_dailysales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenses',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
