# Generated by Django 4.2.3 on 2023-08-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0005_dailyexpenses_modified_at_dailysales_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexpenses',
            old_name='modified_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dailysales',
            old_name='modified_at',
            new_name='created_at',
        ),
    ]
