# Generated by Django 4.2.3 on 2023-12-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(default=None, upload_to="files/"),
        ),
    ]
